[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"


# SPA catch-all — harus paling bawah
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
